version: '3'

services:
 app:
    build:
     context: .
     dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SECRET_PG_PASSWD}
      - POSTGRES_DB=database
      - POSTGRES_HOST=db
    ports:
      - '5000:5000'
    depends_on:
       - db

 db:
    image: postgres:9.5.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SECRET_PG_PASSWD}
      - POSTGRES_DB=database

volumes:
  postgres_data: